name 'aws_chef_jenkins'
maintainer 'Arjen de Rijke'
maintainer_email 'arjenderijke@gmail.com'
license 'all_rights'
description 'Installs/Configures aws_chef_jenkins'
long_description 'Installs/Configures aws_chef_jenkins'
version '0.1.0'

depends 'jenkins', '~> 2.4.1'
depends 'line',    '~> 0.6.3'
